### ISSUE TITLE
CARVI-000006 Create Rest to Db full chain of functionality for GeoRefDms service

### ISSUE THREAD

**Issue by koiva** [koiva/carviator#7]
#### Predefinition
For the following list of entities:
- Continent
- Country
- Point
- District
- Locality
- Street

Via the following list of repositories:
- Continent
- Country
- Point
- District
- Locality
- Street
---
#### Tasks
- [ ] Create service which is responsible for Create, Update, Logically Deletion, Get information about single record in *Continents*
- [ ] Create service which is responsible for Create, Update, Logically Deletion, Get information about single record in *Countries*
- [ ] Create service which is responsible for Create, Update, Logically Deletion, Get information about single record in *Points*
- [ ] Create service which is responsible for Create, Update, Logically Deletion, Get information about single record in *Districts*
- [ ] Create service which is responsible for Create, Update, Logically Deletion, Get information about single record in *Localities*
- [ ] Create service which is responsible for Create, Update, Logically Deletion, Get information about single record in *Streets*
